apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  labels:
    app.kubernetes.io/name: go-api
  namespace: go-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: go-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-api
    spec:
      containers:
        - name: go-api
          image: ghcr.io/tomgoren/go-sample-api:latest
          ports:
            - containerPort: 8080
