apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  namespace: go-api
spec:
  selector:
    app.kubernetes.io/name: go-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
